name: Deploy Trumpbot Backend

on:
  push:
    branches: [main]

jobs:
  Deploy:
    #needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin main &&
            docker build -t vairasza/trumpbot_backend .
            docker run -p 5037:5037 -d vairasza/trumpbot_backend
          '
