name: Deploy Trumpbot Backend

on:
  push:
    branches: [main]

jobs:
  Deploy:
    #needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/trumpbot_backend &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin main &&
            chmod +x ./start_script.sh &&
            bash ./start_script.sh
          '
